version: '3.9'

services:
  api:
    container_name: api
    hostname: api
    image: api:latest
    restart: always

    build:
      context: ./
      target: development
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: ['yarn', 'run', 'dev']
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - api-network

volumes:
  node_modules:

networks:
  api-network:
    driver: bridge
